flysystem:
    storages:
        sylius_digital_product.storage.uploaded_file:
            adapter: 'local'
            options:
                directory: '%sylius_digital_product_plugin.uploaded_file.product_files_path%'
        sylius_digital_product.storage.order_file:
            adapter: 'local'
            options:
                directory: '%sylius_digital_product_plugin.uploaded_file.order_files_path%'
        sylius_digital_product.storage.chunks:
            adapter: 'local'
            options:
                directory: '%sylius_digital_product_plugin.uploaded_file.chunks_path%'
