

sylius_admin_product_digital_download:
    path: /products/digital/uploaded/download/{id}
    methods: [ GET ]
    defaults:
        _controller: sylius_digital_product_plugin.controller.action.uploaded_digital_file_download
        _sylius:
            section: admin
            permission: true
            redirect: referrer
