sylius_admin_digital_product_download:
    path: /products/digital/uploaded/download/{id}
    methods: [ GET ]
    defaults:
        _controller: sylius_digital_product_plugin.controller.admin.action.uploaded_digital_file_download
        _sylius:
            section: admin
            permission: true
            redirect: referrer

sylius_admin_digital_product_chunked_upload:
    path: /ajax/upload/chunk
    methods: [ POST ]
    defaults:
        _controller: sylius_digital_product_plugin.controller.action.chunked_upload
        _sylius:
            section: admin
            permission: true
