sylius_digital_product_shop_download_order_item_file:
    path: /{_locale}/account/orders/{number}/download/{uuid}
    methods: [ GET ]
    defaults:
        _controller: sylius_digital_product_plugin.controller.shop.action.download_order_item_file
        _sylius:
            permission: true
            redirect: referrer
